- name: Install nginx
  hosts: web_servers
  become: yes

- tasks:
  - name: Update system package
    yum:
        update_cache: yes
    when: ansible_os_family == "RedHat"

  - name: Install nginx
    yum: 
        name: nginx
        state: present
    when: ansible_os_family == "RedHat"

  - name: Start and enable Nginx
    service:
        name: nginx
        state: started
        enabled: yes

handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
        
        
